STRINGS.CARNEYTAB = "制造"

STRINGS.NAMES.WHITEBERET = "白色贝雷帽"
STRINGS.RECIPE_DESC.WHITEBERET = "出门不能忘记戴帽子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHITEBERET = "涤纶的质感，不像是手工纺织品"

STRINGS.NAMES.ANGELCRYSTAL = "天使水晶"
STRINGS.RECIPE_DESC.ANGELCRYSTAL = "蕴含影响心智的能量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANGELCRYSTAL = "闪亮的石头"

STRINGS.NAMES.WINDYKNIFE = "微风短剑"
STRINGS.RECIPE_DESC.WINDYKNIFE = "顺手的短剑怎么用都顺手"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WINDYKNIFE = "精巧得难以置信"

STRINGS.NAMES.LUCKYFISH = "幸运鱼"
STRINGS.RECIPE_DESC.LUCKYFISH = "会带来好运"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUCKYFISH = "它看起来带着一点幸运的气息"

STRINGS.NAMES.NYLON = "尼龙背包"
STRINGS.RECIPE_DESC.NYLON = "加强了压缩带的防水型内框架背包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NYLON = "很大却很轻，非常厚实"

STRINGS.NAMES.NYLON_PLUS = "尼龙背包++"
STRINGS.RECIPE_DESC.NYLON_PLUS = "更大的尼龙背包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NYLON_PLUS = "升级后的背包，能装更多东西。"

STRINGS.CHARACTER_TITLES.carney = "卡尼猫"
STRINGS.CHARACTER_NAMES.carney = "Carney"
STRINGS.CHARACTER_DESCRIPTIONS.carney = "*吃鱼与战斗成长\n*喜欢一直在旅行"
STRINGS.CHARACTER_QUOTES.carney = "正在到处旅行着"

STRINGS.NAMES.CARNEYTEMP = "卡尼猫知识"
STRINGS.RECIPE_DESC.WHITEBERET = "历程经验"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHITEBERET = "恢复到以前等级"

STRINGS.NAMES.WHITEBERET_PLUS = "堆堆帽"
STRINGS.RECIPE_DESC.WHITEBERET_PLUS = "保护你的耳朵!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHITEBERET_PLUS = "谁能拒绝毛茸茸的温暖呢?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.carney = 
{
	GENERIC = "这是谁!",
	ATTACKER = "打啊",
	MURDERER = "谋杀啊!",
	REVIVER = "啥玩意儿?!",
	GHOST = "我是鬼",
}

STRINGS.NAMES.carney = "Carney"

STRINGS.CARNEYSTRINGS={
[1] = "等级提升啦!",
[2] = "总算找回了自己!",
[3] = " 的卡尼猫知识",
[4] = "别乱动，真正的 ",
[5] = " 不会放过你",
[6] = "不是你的，只有真正的 ",
[7] = " 才有资格",
[8] = "一边玩去，我在等真正的 ",
[9] = " 回来",
[10] = "别人正在用",
[11] = "我现在还不能使用它",
}

STRINGS.CARNEYUI={
[1] = "玩法说明",
}

STRINGS.CARNEYBUGJUMP = {
	TARGET_LOST = "目标消失了？",
	MISS        = "没抓到",
	CATCH       = "抓到啦！",
	BLOCKED     = "有障碍物挡着",
}

